# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: apps-ingress-tls
#   namespace: default
# spec:
#   secretName: apps-ingress-tls
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-stg
#   dnsNames:
#   - dev.forms-app.apps.exekube.us
#   - dev.guestbook.apps.exekube.us
#   acme:
#     config:
#     - http01:
#         ingress: apps-ingress
#       domains:
#       - dev.forms-app.apps.exekube.us
#       - dev.guestbook.apps.exekube.us
